### ISSUE TITLE
Can't use a complex generator as a part of ?LETSHRINK

### ISSUE THREAD

**Issue by ElectronicRU** [manopapad/proper#137] opened 2017-01-31 17:16 UTC
Using the following generator code:
```erlang

json(Size) ->
  oneof(
    [null,
     number(),
     unicode_binary(Size),
     ?LETSHRINK(V, json_list(Size), V),
     ?LETSHRINK(M, json_maplist(Size), maps:from_list(M))]
  ).

json_list(0) ->
  [];
json_list(Size) ->
  ?LET(X, range(0, Size),
       [json(X) | json_list(Size - X)]).

json_maplist(0) ->
  [];
json_maplist(Size) ->
  ?LET(ESize, range(1, Size),
       ?LET(KeySize, range(1, ESize),
            [{non_empty(key(KeySize)), json(ESize - KeySize)} | json_maplist(Size - ESize)])).

key(Size) ->
  union([<<"after">>,
         <<"period">>,
         <<"cron">>,
         unicode_binary(Size)]).

unicode_binary(Size) ->
  ?LET(X, resize(Size, string()), unicode:characters_to_binary(X)).
```
works fine as long as the property test doesn't fail, but results in the following error if it does:
```
{'EXIT',
                                          {function_clause,
                                           [{proper_shrink,
                                             '-to_part_shrinker/3-lc$^0/1-0-',
                                             [{'$used',6,
                                               {'$used',6,
                                                [{{'$used',[1],<<1>>},
                                                  {'$used',[],[]}}]}}],
                                             [{file,
                                               "/Users/-/git/sched_spec/_build/test/lib/proper/src/proper_shrink.erl"},
                                              {line,148}]},
                                            {proper_shrink,to_part_shrinker,
                                             3,
                                             [{file,
                                               "/Users/-/git/sched_spec/_build/test/lib/proper/src/proper_shrink.erl"},
                                              {line,148}]},
```

From my understanding, this happens because shrink_parts assumes the parts themselves are a raw list type (which is not the case here). I understand the dilemma of "shrink parts vs. shrink to parts", but it seems to me that shrinking to parts first is how it should be done (because reducing the number of parts before we shrink to one of them is generally not helpful). I.E. we should call clean_instance on the parts before iterating over them.

**Comment by kostis** [comment] 2017-01-31 18:56
Can you please provide some (preferably self-contained) test case so that we can reproduce and PropErly(TM) debug this?

Also, note that `?LETSHRINK`'s documentation specifies that its first and second argument are _lists_ of variables and _lists_ of types, respectively, while those in your code are not.  Can this be a reason for what you are experiencing?  (It's difficult to know without a test case.)

Finally, I could not help noticing the following:
```erl
     unicode_binary(Size),
     ?LETSHRINK(V, json_list(Size), V),
```
why the reason to write such a complicated line (for `json_list`)?  Just because of the `[]` return in the 0 case?

**Comment by ElectronicRU** [comment] 2017-01-31 19:03
Well, this is a test case for the generator. For the property, you just need something that fails on shrinkable objects, like, hm. 
```erlang
?FORALL(X, ?SIZED(S, json(S)), not is_map(X) end)
```

The purpose of this line is to have list reduced to its elements in case of shrinking.

**Comment by kostis** [comment] 2017-01-31 19:19
It's as I wrote.  You need to follow the documentation.  Change the two lines to:
```erl
     ?LETSHRINK([V], [json_list(Size)], V),
     ?LETSHRINK([M], [json_maplist(Size)], maps:from_list(M))]
```

Please confirm, so that I close this issue if it is resolved.

**Comment by ElectronicRU** [comment] 2017-02-01 14:54
This is not what I want though. I want to shrink to ELEMENTS of V, not to V itself.

**Comment by kostis** [comment] 2017-02-01 15:19
Then you need to find some other way of expressing your generators & shrinkers, not the one above. If you choose to use the `?LETSHRINK` macro, you need to supply it with lists in its first two arguments.

**Comment by kostis** [comment] 2017-02-04 23:35
I will close the issue now.  Open another one if you encounter some other problem with shrinking.

**Closed by kostis** 2017-02-04 23:35 UTC
